import pandas as pd
import numpy as np
import requests
from io import BytesIO
from PIL import Image

# -----------------------------
# Color utils
# -----------------------------
def _rgb_to_hsv(r, g, b):
    r, g, b = r/255.0, g/255.0, b/255.0
    mx = max(r, g, b); mn = min(r, g, b); df = mx - mn
    if df == 0:
        h = 0
    elif mx == r:
        h = (60 * ((g - b) / df) + 360) % 360
    elif mx == g:
        h = (60 * ((b - r) / df) + 120) % 360
    else:
        h = (60 * ((r - g) / df) + 240) % 360
    s = 0 if mx == 0 else df / mx
    v = mx
    return h, s, v

def _classify_basic_colors(pixels_rgb):
    # returns booleans for basic buckets
    has = {"red": False, "white": False, "blue": False, "green": False, "yellow": False, "black": False}
    for r, g, b in pixels_rgb:
        h, s, v = _rgb_to_hsv(int(r), int(g), int(b))

        # black / white
        if v < 0.18:
            has["black"] = True
            continue
        if v > 0.82 and s < 0.20:
            has["white"] = True
            continue

        # chromatic threshold
        if s < 0.25:
            continue

        if (h >= 330 or h < 20):
            has["red"] = True
        elif 200 <= h < 260:
            has["blue"] = True
        elif 80 <= h < 160:
            has["green"] = True
        elif 35 <= h < 70:
            has["yellow"] = True
    return has

def analyze_flag(url: str, sample_pixels: int = 12000, quantize_colors: int = 12, dom_thr_pct: float = 0.015):
    """
    Returns:
      n_colors_approx (int)
      has_red/white/blue/green/yellow/black (bools)
      only_rwb (bool)
      no_rwb (bool)
    """
    r = requests.get(url, timeout=10)
    r.raise_for_status()
    im = Image.open(BytesIO(r.content)).convert("RGBA")

    # normalize size
    im = im.resize((240, int(240 * im.size[1] / im.size[0])), Image.BILINEAR)

    arr = np.array(im)  # HxWx4
    alpha = arr[..., 3]
    rgb = arr[..., :3][alpha > 10]
    if rgb.size == 0:
        raise ValueError("empty flag pixels")

    # sample
    if rgb.shape[0] > sample_pixels:
        idx = np.random.choice(rgb.shape[0], sample_pixels, replace=False)
        rgb_s = rgb[idx]
    else:
        rgb_s = rgb

    has = _classify_basic_colors(rgb_s)

    # quantize for approximate dominant color count
    im_q = im.convert("RGB").quantize(colors=quantize_colors, method=2)
    counts = np.bincount(np.array(im_q).flatten())
    thr = max(1, int(dom_thr_pct * counts.sum()))
    dominant = int((counts >= thr).sum())
    n_colors = max(1, dominant)

    only_rwb = (has["red"] and has["white"] and has["blue"] and
                not has["green"] and not has["yellow"] and not has["black"])
    no_rwb = (not has["red"] and not has["white"] and not has["blue"])

    return n_colors, has, only_rwb, no_rwb

# -----------------------------
# Build sets -> python file
# -----------------------------
def py_set(name, items):
    items = sorted(set(items))
    body = ", ".join(f'"{x}"' for x in items)
    return f"{name} = {{{body}}}\n"

def main():
    df = pd.read_csv("countries_master.csv")
    df["iso3"] = df["iso3"].astype(str).str.strip().str.upper()
    df = df.dropna(subset=["iso3", "flag_png"])
    df = df[df["flag_png"].astype(str).str.startswith("http")]

    # buckets
    ncolor_buckets = {}  # int -> set(iso3)
    only_rwb = set()
    no_rwb = set()

    has_red = set(); has_white = set(); has_blue = set()
    has_green = set(); has_yellow = set(); has_black = set()

    failures = []

    for _, row in df.iterrows():
        iso3 = row["iso3"]
        url = str(row["flag_png"])

        try:
            n_colors, has, only, no = analyze_flag(url)

            ncolor_buckets.setdefault(int(n_colors), set()).add(iso3)

            if has["red"]: has_red.add(iso3)
            if has["white"]: has_white.add(iso3)
            if has["blue"]: has_blue.add(iso3)
            if has["green"]: has_green.add(iso3)
            if has["yellow"]: has_yellow.add(iso3)
            if has["black"]: has_black.add(iso3)

            if only: only_rwb.add(iso3)
            if no: no_rwb.add(iso3)

        except Exception as e:
            failures.append((iso3, str(e)))

    # write output file
    with open("flag_color_sets.py", "w", encoding="utf-8") as f:
        f.write("# Auto-generated by build_flag_color_sets.py\n\n")

        # dict style bucket
        f.write("FLAG_NCOLORS_ISO3 = {\n")
        for k in sorted(ncolor_buckets.keys()):
            vals = sorted(ncolor_buckets[k])
            f.write(f"    {k}: {{{', '.join([f'\"{v}\"' for v in vals])}}},\n")
        f.write("}\n\n")

        f.write(py_set("FLAG_ONLY_RED_WHITE_BLUE_ISO3", only_rwb))
        f.write(py_set("FLAG_WITHOUT_RED_WHITE_BLUE_ISO3", no_rwb))

        # optional base-color sets (useful for filters)
        f.write("\n# Optional: basic-color presence sets\n")
        f.write(py_set("FLAG_HAS_RED_ISO3", has_red))
        f.write(py_set("FLAG_HAS_WHITE_ISO3", has_white))
        f.write(py_set("FLAG_HAS_BLUE_ISO3", has_blue))
        f.write(py_set("FLAG_HAS_GREEN_ISO3", has_green))
        f.write(py_set("FLAG_HAS_YELLOW_ISO3", has_yellow))
        f.write(py_set("FLAG_HAS_BLACK_ISO3", has_black))

    if failures:
        print("WARN: some flags failed to process:", len(failures))
        for iso3, err in failures[:30]:
            print(" -", iso3, err)
        print("... (showing first 30)")

    print("OK: wrote flag_color_sets.py")

if __name__ == "__main__":
    main()
